### ISSUE TITLE
Compile Issues On Linux

### ISSUE THREAD

**Issue by cgruelle** [hjd1964/SmartWebServer#1]
When trying to compile the SmartWebServer with the Ardunio IDE running on Linux, I'm receiving the following errors:

SmartWebServer:52:35: fatal error: src/encoders/encoders.h: No such file or directory
 #include "src/encoders/encoders.h"
                                   ^
compilation terminated.
exit status 1
src/encoders/encoders.h: No such file or directory

src/encoders/encoders.h does not exist, but src/encoders/Encoders.h does. If you change the include in SmartWebServer.ino to src/encoders/Encoders.h compilation continues until the following error.

sketch/src/pages/Err404.cpp:16:42: fatal error: ../ethernetServers/webServer.h: No such file or directory
compilation terminated.
exit status 1

In src/ethernetServers webServer.h does not exist, but WebServer.h does. Not sure how many other case issues there are, I stopped with those two.

**Comment by hjd1964** [comment]
Yeah that happens...  windows isn't case sensitive so those little typos go
unnoticed.

**Comment by hjd1964** [comment]
I've committed changes to address this, not 100% sure all have been addressed but those mentioned above should be taken care of.

**Comment by cgruelle** [comment]
I was able to successfully compile this on Linux now. I have it running on my WeMos D1 mini now. Thanks, Howard!
