### ISSUE TITLE
Comment for LED_STATUS_ON_STATE correct?

### ISSUE THREAD

**Issue by jesco-t** [hjd1964/SmartWebServer#2]
The comment for the LED_STATUS_ON_STATE seems reversed. The setting has to be HIGH so that the indicator LED is OFF when connected; the comment say it should be HIGH to leave the LED on. The line should read:

#define LED_STATUS_ON_STATE           LOW //         LOW, Use HIGH so indicator stays OFF when connected if needed.            Option

This may be particular to my Wemos boards, I am not sure. I tested this on two differently sourced boards which are definetely not from the same assembly when looking at the SMT placement.

Regards, Jesco

**Comment by hjd1964** [comment]
Board dependent, so not changing.
