### ISSUE TITLE
Opened  SmartWebServer.ino has only 3 files

### ISSUE THREAD

**Issue by tsatatwer** [hjd1964/SmartWebServer#5]
Hi ,

when I opened SmartWebServer.ino it opened only 3 files **SmartWebServer** and **Config.h** and **Extended.Config.h** ?? others files not opened in project for example **encoders** **commands**   ?? al files inside **SmartWebServer**  directory .

**Comment by vzr314** [comment]
There is nothing wrong with that. You don't need to open any other file. They are stored in src directory and linked via SmartWebServer.ino sketch so everything needed will be uploaded and You should not edit anything but Config.h and Extended.Config.h.

**Comment by tsatatwer** [comment]
Ok thanks indeed for the fast replay I will close this issue.
